<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<Version>1.2.5</Version>
		<Description>Assembly Information &amp; Loader via Reflection</Description>
		<PackageTags>AssemblyLoader C# AssemblyInfo</PackageTags>
		<PackageReleaseNotes>Multi-target framework support for .NET Standard and .NET 11.</PackageReleaseNotes>
	</PropertyGroup>

</Project>
