name: .NET Build

on:
  push:
    branches: master

  pull_request:

  workflow_dispatch:
  
jobs:        
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [self-hosted]
            BuildConfiguration: [ Release ]
        max-parallel: 2
        
    steps:
   
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: '0'

    - name: Install Configurations
      run: |
        Copy-Item -Path "../../../../NuGet.Config.template" -Destination "../NuGet.Config"
        Copy-Item -Path "../../../../Directory.Build.props" -Destination ".."
        Copy-Item -Path "../../../../Directory.Build.targets" -Destination ".." 
      
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      id: build
      run: |
        dotnet build --no-restore --configuration ${{ matrix.BuildConfiguration }}
