name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
      
    steps:

    - name: Get BIN_DIR
      id: bin-dir
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          bin_dir='${{ github.workspace }}/AssemblyLoader/bin/${{ matrix.BuildConfiguration }}'
        elif [ "$RUNNER_OS" == "Windows" ]; then
          bin_dir='${{ github.workspace }}\AssemblyLoader\bin\${{ matrix.BuildConfiguration }}'
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
        echo "$bin_dir"
        echo "BIN_DIR=$bin_dir" >> $GITHUB_ENV

        
    - name: Get BRANCH_NAME
      id: branch-name
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          split=(${GITHUB_REF_NAME//\// })
        elif [ "$RUNNER_OS" == "Windows" ]; then
          split=(${GITHUB_REF_NAME////// })
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
        index=$((${#split[@]}-1))
        branch_name=${split[$index]}
        echo "$branch_name"
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
        
    - name: Get Build Artifacts
      if: false
      shell: bash
      run: |
        mkdir -p Packages
        curl -sS -O -L 'https://github.com/${{ github.repository_owner }}/Build-Configs/blob/master/{snKey.snk,Kitty.png}'
